#!/usr/bin/env python3
# BBB-AIRGAP: emits the generated half of libjade/selfcheck/slip39.c, the SLIP-0039 test
# vector table.  Stdout goes between the two BEGIN/END GENERATED markers in that file; the
# rest of it is hand written and is not touched here.
#
# Source: pijade/tools/fixtures/slip39_vectors.json, taken verbatim from the root of
# trezor/python-shamir-mnemonic (blob d98c387aa1feb32ca9e6e4410cff870dfc6fb358, commit
# 1525df19df504b1f69b49179140119959f317f24, sha256
# 13ebecebdd869dd2bc2cdf69e7ce3a158cf106cac76c39d17682b1c6cdabbdc4).  That repository is
# MIT (SatoshiLabs 2019); the licence travels next to the fixture as
# fixtures/slip39_vectors.LICENSE, which is what the MIT notice clause asks for.
#
# Each record there has four fields: a description, the mnemonics, the master secret as hex
# ("" when the record must be rejected), and the xprv that secret derives to.  Only the
# middle two are emitted; see the header of the selfcheck for why the xprv is out of scope.
#
# The output is not byte for byte what ends up in the selfcheck: once pasted, the file is run
# through clang-format-19 like every other source here, and a mnemonic too long for the column
# limit is split into two adjacent string literals ("... erode duke " "ajar critical ...").
# C joins those back into one string, so re-running this to check the table still matches means
# deleting the "" seams first and then collapsing whitespace.  Comparing line by line, or
# collapsing whitespace alone, reports differences that are not there.

import hashlib
import io
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, 'fixtures', 'slip39_vectors.json')

raw = io.open(SRC, 'rb').read()
records = json.loads(raw.decode('utf-8'))

valid = sum(1 for r in records if r[2])
invalid = len(records) - valid

out = []
out.append('// Generated by pijade/tools/gen_slip39_vectors.py from')
out.append('// pijade/tools/fixtures/slip39_vectors.json (sha256 %s),'
           % hashlib.sha256(raw).hexdigest())
out.append('// %d records: %d valid, %d to be rejected.  Do not edit by hand.'
           % (len(records), valid, invalid))
for i, record in enumerate(records):
    mnemonics, secret = record[1], record[2]
    out.append('static const char* const VEC%02d[] = {' % i)
    for mnemonic in mnemonics:
        out.append('    "%s",' % mnemonic)
    out.append('    NULL,')
    out.append('};')

out.append('')
out.append('static const slip39_vector_t VECTORS[] = {')
for i, record in enumerate(records):
    out.append('    { VEC%02d, "%s" },' % (i, record[2]))
out.append('};')

sys.stdout.write('\n'.join(out) + '\n')
