# BBB-AIRGAP M3 emulator scenario driver. Runs in the container: /jade = repository, /probe = Mac
# scratch mount (frames are generated by mine_qr.py; display dumps are written here).
# Usage: sh m3_mine.sh <tag> <frame.gray> <mode>; nci daemon (waits for real presses).
# Modes: no | stop | solve | idle | dimstop | long | term
set -u
TAG=$1; FRAME=$2; MODE=$3
D=/jade/build_linux_nci_log/libjade/libjade_daemon
SOCK=/tmp/m3_$TAG.sock; LOG=/tmp/m3_$TAG.log
J="python3 /jade/pijade/tools/jadectl.py $SOCK"
SEED="seed:abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
[ -S $SOCK ] && unlink $SOCK
$D --socketfile $SOCK --log-level info > $LOG 2>&1 &
DP=$!
for i in $(seq 1 200); do [ -S $SOCK ] && break; sleep 0.1; done
[ -S $SOCK ] || { echo "DAEMON DID NOT START"; exit 1; }
cd /probe
python3 /jade/pijade/tools/menu_audit.py $SOCK $LOG $TAG "$SEED" shot:home | tail -1
# Scan: frames before and after the click
$J camfile:$FRAME:12 btn:right wait:0.5 btn:click camfile:$FRAME:12 wait:2 shot:${TAG}_confirm > /dev/null
# From confirmation to mining: right (Yes) + click
START="btn:right wait:0.3 btn:click"
case $MODE in
  no)    $J btn:click wait:1 shot:${TAG}_after > /dev/null ;;
  stop)  $J $START wait:3 shot:${TAG}_mine1 wait:3 shot:${TAG}_mine2 btn:click wait:1 \
           shot:${TAG}_after > /dev/null ;;
  solve) $J $START wait:3 shot:${TAG}_sol btn:down wait:0.3 shot:${TAG}_sol2 btn:click wait:1 > /dev/null
         ARGS=""; for i in $(seq -w 0 79); do ARGS="$ARGS shot:${TAG}_qr$i wait:0.25"; done
         $J $ARGS > /dev/null; $J btn:click wait:1 shot:${TAG}_after > /dev/null ;;
  idle)  $J $START wait:180 shot:${TAG}_mine1 btn:click wait:1 shot:${TAG}_after > /dev/null ;;
  dimstop) $J $START wait:130 shot:${TAG}_mine1 btn:click wait:1 shot:${TAG}_wake btn:click wait:1 \
             shot:${TAG}_after > /dev/null ;;
  long)  $J $START wait:660 shot:${TAG}_mine1 btn:click wait:1 shot:${TAG}_wake btn:click wait:1 \
           shot:${TAG}_after > /dev/null ;;
  term)  $J $START wait:3 shot:${TAG}_mine1 > /dev/null
         T0=$(date +%s); kill -TERM $DP; wait $DP 2>/dev/null
         echo "exit after SIGTERM: $(( $(date +%s) - T0 )) s" ;;
esac
echo "--- log ---"
grep -n "Detected\|Mining\|mining\|Failed\|idle\|Idle\|ERROR" $LOG | grep -v "wire.c" | tail -14
kill $DP 2>/dev/null; wait $DP 2>/dev/null
echo "HARNESS_DONE"
