# BBB-AIRGAP M3 emulator scan driver. Runs in the container: /jade = repository, /probe = Mac
# scratch mount (frames are generated by mine_qr.py; display dumps are written here).
# Usage: sh m3_scan.sh <tag> <camera-step>; fresh daemon, seed, Scan QR, feed frames, log summary
set -u
TAG=$1; CAMSTEP=$2
D=/jade/build_linux_nci_log/libjade/libjade_daemon
SOCK=/tmp/m3_$TAG.sock; LOG=/tmp/m3_$TAG.log
SEED="seed:abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
[ -S $SOCK ] && unlink $SOCK
$D --socketfile $SOCK --log-level info > $LOG 2>&1 &
DP=$!
for i in $(seq 1 200); do [ -S $SOCK ] && break; sleep 0.1; done
[ -S $SOCK ] || { echo "DAEMON DID NOT START"; exit 1; }
cd /probe
python3 /jade/pijade/tools/menu_audit.py $SOCK $LOG $TAG "$SEED" shot:home | tail -2
python3 /jade/pijade/tools/jadectl.py $SOCK $CAMSTEP btn:right wait:0.5 btn:click $CAMSTEP wait:2 \
  shot:${TAG}_scan wait:1 shot:${TAG}_scan2
echo "--- log ---"
grep -n "Detected\|Unhandled\|mining\|Mining\|qrscan\|bcur\|Failed\|E (" $LOG | tail -12
kill $DP 2>/dev/null; wait $DP 2>/dev/null
echo "HARNESS_DONE"
