#include <string.h>

#include "selfcheck.h"
#include "slip39.h"

#include <wally_core.h>

// BBB-AIRGAP: vectors for the SLIP-0039 core (main/slip39.c).  These are the published
// SLIP-0039 test vectors, so no wallet of anyone's is written down here and the emulator can
// be handed them without a secret reaching this machine.
//
// The table below is generated, not typed: pijade/tools/gen_slip39_vectors.py reads
// pijade/tools/fixtures/slip39_vectors.json and emits it verbatim.  That fixture is the
// vectors.json at the root of trezor/python-shamir-mnemonic, taken byte for byte; the
// repository is MIT (SatoshiLabs 2019) and the licence travels next to the fixture as
// fixtures/slip39_vectors.LICENSE.  Trezor firmware carries the same 45 records in
// core/tests/slip39_vectors.py and the two fields used here were measured to be identical,
// but that copy is deliberately not the source: core/ is GPLv3 by the monorepo's own
// LICENSE.md, and this fork is MIT.
//
// The passphrase is "TREZOR".  The fixture does not name it; it is read from the test that
// consumes the same records in that repository, test_shamir.py, where test_vectors() calls
// combine_mnemonics() with b"TREZOR".
//
// 45 records: 15 are valid and carry the expected master secret, 30 are invalid and must be
// rejected.  Which rejection classes those 30 actually exercise was not claimed anywhere
// until now; test_vectors() counts them by reason and logs the distribution.  Two classes no
// record can reach get their own checks below, SLIP39_ERR_WORD and SLIP39_ERR_DUPLICATE.  The
// remaining two, SLIP39_ERR_GROUP_FULL and SLIP39_ERR_GROUPS_FULL, need a share set that
// overfills a group and no published record carries one; they are not exercised here.
//
// What is measured stops at the master secret.  Each upstream record also carries the xprv
// that secret derives to, and that field is deliberately not emitted: turning a secret into a
// key is keychain_derive_from_seed()'s business, not this module's.

#define VECTOR_PASSPHRASE "TREZOR"

typedef struct {
    const char* const* mnemonics;
    const char* secret; // hex, empty for a record that must be rejected
} slip39_vector_t;

// BEGIN GENERATED
// Generated by pijade/tools/gen_slip39_vectors.py from
// pijade/tools/fixtures/slip39_vectors.json (sha256 13ebecebdd869dd2bc2cdf69e7ce3a158cf106cac76c39d17682b1c6cdabbdc4),
// 45 records: 15 valid, 30 to be rejected.  Do not edit by hand.
static const char* const VEC00[] = {
    "duckling enlarge academic academic agency result length solution fridge kidney coal piece deal husband erode duke "
    "ajar critical decision keyboard",
    NULL,
};
static const char* const VEC01[] = {
    "duckling enlarge academic academic agency result length solution fridge kidney coal piece deal husband erode duke "
    "ajar critical decision kidney",
    NULL,
};
static const char* const VEC02[] = {
    "duckling enlarge academic academic email result length solution fridge kidney coal piece deal husband erode duke "
    "ajar music cargo fitness",
    NULL,
};
static const char* const VEC03[] = {
    "shadow pistol academic always adequate wildlife fancy gross oasis cylinder mustang wrist rescue view short owner "
    "flip making coding armed",
    "shadow pistol academic acid actress prayer class unknown daughter sweater depict flip twice unkind craft early "
    "superior advocate guest smoking",
    NULL,
};
static const char* const VEC04[] = {
    "shadow pistol academic always adequate wildlife fancy gross oasis cylinder mustang wrist rescue view short owner "
    "flip making coding armed",
    NULL,
};
static const char* const VEC05[] = {
    "adequate smoking academic acid debut wine petition glen cluster slow rhyme slow simple epidemic rumor junk tracks "
    "treat olympic tolerate",
    "adequate stay academic agency agency formal party ting frequent learn upstairs remember smear leaf damage anatomy "
    "ladle market hush corner",
    NULL,
};
static const char* const VEC06[] = {
    "peasant leaves academic acid desert exact olympic math alive axle trial tackle drug deny decent smear dominant "
    "desert bucket remind",
    "peasant leader academic agency cultural blessing percent network envelope medal junk primary human pumps jacket "
    "fragment payroll ticket evoke voice",
    NULL,
};
static const char* const VEC07[] = {
    "liberty category beard echo animal fawn temple briefing math username various wolf aviation fancy visual holy "
    "thunder yelp helpful payment",
    "liberty category beard email beyond should fancy romp founder easel pink holy hairy romp loyalty material victim "
    "owner toxic custody",
    "liberty category academic easy being hazard crush diminish oral lizard reaction cluster force dilemma deploy "
    "force club veteran expect photo",
    NULL,
};
static const char* const VEC08[] = {
    "average senior academic leaf broken teacher expect surface hour capture obesity desire negative dynamic dominant "
    "pistol mineral mailman iris aide",
    "average senior academic agency curious pants blimp spew clothes slice script dress wrap firm shaft regular "
    "slavery negative theater roster",
    NULL,
};
static const char* const VEC09[] = {
    "music husband acrobat acid artist finance center either graduate swimming object bike medical clothes station "
    "aspect spider maiden bulb welcome",
    "music husband acrobat agency advance hunting bike corner density careful material civil evil tactics remind hawk "
    "discuss hobo voice rainbow",
    "music husband beard academic black tricycle clock mayor estimate level photo episode exclude ecology papa source "
    "amazing salt verify divorce",
    NULL,
};
static const char* const VEC10[] = {
    "device stay academic always dive coal antenna adult black exceed stadium herald advance soldier busy dryer "
    "daughter evaluate minister laser",
    "device stay academic always dwarf afraid robin gravity crunch adjust soul branch walnut coastal dream costume "
    "scholar mortgage mountain pumps",
    NULL,
};
static const char* const VEC11[] = {
    "hour painting academic academic device formal evoke guitar random modern justice filter withdraw trouble identify "
    "mailman insect general cover oven",
    "hour painting academic agency artist again daisy capital beaver fiber much enjoy suitable symbolic identify photo "
    "editor romp float echo",
    NULL,
};
static const char* const VEC12[] = {
    "guilt walnut academic acid deliver remove equip listen vampire tactics nylon rhythm failure husband fatigue alive "
    "blind enemy teaspoon rebound",
    "guilt walnut academic agency brave hamster hobo declare herd taste alpha slim criminal mild arcade formal romp "
    "branch pink ambition",
    NULL,
};
static const char* const VEC13[] = {
    "eraser senior beard romp adorn nuclear spill corner cradle style ancient family general leader ambition exchange "
    "unusual garlic promise voice",
    NULL,
};
static const char* const VEC14[] = {
    "eraser senior decision scared cargo theory device idea deliver modify curly include pancake both news skin "
    "realize vitamins away join",
    "eraser senior decision roster beard treat identify grumpy salt index fake aviation theater cubic bike cause "
    "research dragon emphasis counter",
    NULL,
};
static const char* const VEC15[] = {
    "eraser senior decision shadow artist work morning estate greatest pipeline plan ting petition forget hormone "
    "flexible general goat admit surface",
    "eraser senior beard romp adorn nuclear spill corner cradle style ancient family general leader ambition exchange "
    "unusual garlic promise voice",
    NULL,
};
static const char* const VEC16[] = {
    "eraser senior decision roster beard treat identify grumpy salt index fake aviation theater cubic bike cause "
    "research dragon emphasis counter",
    "eraser senior ceramic snake clay various huge numb argue hesitate auction category timber browser greatest hanger "
    "petition script leaf pickup",
    "eraser senior ceramic shaft dynamic become junior wrist silver peasant force math alto coal amazing segment yelp "
    "velvet image paces",
    "eraser senior ceramic round column hawk trust auction smug shame alive greatest sheriff living perfect corner "
    "chest sled fumes adequate",
    "eraser senior decision smug corner ruin rescue cubic angel tackle skin skunk program roster trash rumor slush "
    "angel flea amazing",
    NULL,
};
static const char* const VEC17[] = {
    "eraser senior decision smug corner ruin rescue cubic angel tackle skin skunk program roster trash rumor slush "
    "angel flea amazing",
    "eraser senior beard romp adorn nuclear spill corner cradle style ancient family general leader ambition exchange "
    "unusual garlic promise voice",
    "eraser senior decision scared cargo theory device idea deliver modify curly include pancake both news skin "
    "realize vitamins away join",
    NULL,
};
static const char* const VEC18[] = {
    "eraser senior beard romp adorn nuclear spill corner cradle style ancient family general leader ambition exchange "
    "unusual garlic promise voice",
    "eraser senior acrobat romp bishop medical gesture pumps secret alive ultimate quarter priest subject class "
    "dictate spew material endless market",
    NULL,
};
static const char* const VEC19[] = {
    "theory painting academic academic armed sweater year military elder discuss acne wildlife boring employer fused "
    "large satoshi bundle carbon diagnose anatomy hamster leaves tracks paces beyond phantom capital marvel lips brave "
    "detect luck",
    NULL,
};
static const char* const VEC20[] = {
    "theory painting academic academic armed sweater year military elder discuss acne wildlife boring employer fused "
    "large satoshi bundle carbon diagnose anatomy hamster leaves tracks paces beyond phantom capital marvel lips brave "
    "detect lunar",
    NULL,
};
static const char* const VEC21[] = {
    "theory painting academic academic campus sweater year military elder discuss acne wildlife boring employer fused "
    "large satoshi bundle carbon diagnose anatomy hamster leaves tracks paces beyond phantom capital marvel lips "
    "facility obtain sister",
    NULL,
};
static const char* const VEC22[] = {
    "humidity disease academic always aluminum jewelry energy woman receiver strategy amuse duckling lying evidence "
    "network walnut tactics forget hairy rebound impulse brother survive clothes stadium mailman rival ocean reward "
    "venture always armed unwrap",
    "humidity disease academic agency actress jacket gross physics cylinder solution fake mortgage benefit public busy "
    "prepare sharp friar change work slow purchase ruler again tricycle involve viral wireless mixture anatomy desert "
    "cargo upgrade",
    NULL,
};
static const char* const VEC23[] = {
    "humidity disease academic always aluminum jewelry energy woman receiver strategy amuse duckling lying evidence "
    "network walnut tactics forget hairy rebound impulse brother survive clothes stadium mailman rival ocean reward "
    "venture always armed unwrap",
    NULL,
};
static const char* const VEC24[] = {
    "smear husband academic acid deadline scene venture distance dive overall parking bracelet elevator justice echo "
    "burning oven chest duke nylon",
    "smear isolate academic agency alpha mandate decorate burden recover guard exercise fatal force syndrome fumes "
    "thank guest drift dramatic mule",
    NULL,
};
static const char* const VEC25[] = {
    "finger trash academic acid average priority dish revenue academic hospital spirit western ocean fact calcium "
    "syndrome greatest plan losing dictate",
    "finger traffic academic agency building lilac deny paces subject threaten diploma eclipse window unknown health "
    "slim piece dragon focus smirk",
    NULL,
};
static const char* const VEC26[] = {
    "flavor pink beard echo depart forbid retreat become frost helpful juice unwrap reunion credit math burning spine "
    "black capital lair",
    "flavor pink beard email diet teaspoon freshman identify document rebound cricket prune headset loyalty smell "
    "emission skin often square rebound",
    "flavor pink academic easy credit cage raisin crazy closet lobe mobile become drink human tactics valuable hand "
    "capture sympathy finger",
    NULL,
};
static const char* const VEC27[] = {
    "column flea academic leaf debut extra surface slow timber husky lawsuit game behavior husky swimming already "
    "paper episode tricycle scroll",
    "column flea academic agency blessing garbage party software stadium verify silent umbrella therapy decorate "
    "chemical erode dramatic eclipse replace apart",
    NULL,
};
static const char* const VEC28[] = {
    "smirk pink acrobat acid auction wireless impulse spine sprinkle fortune clogs elbow guest hush loyalty crush "
    "dictate tracks airport talent",
    "smirk pink acrobat agency dwarf emperor ajar organize legs slice harvest plastic dynamic style mobile float bulb "
    "health coding credit",
    "smirk pink beard academic alto strategy carve shame language rapids ruin smart location spray training acquire "
    "eraser endorse submit peaceful",
    NULL,
};
static const char* const VEC29[] = {
    "fishing recover academic always device craft trend snapshot gums skin downtown watch device sniff hour clock "
    "public maximum garlic born",
    "fishing recover academic always aircraft view software cradle fangs amazing package plastic evaluate intend "
    "penalty epidemic anatomy quarter cage apart",
    NULL,
};
static const char* const VEC30[] = {
    "evoke garden academic academic answer wolf scandal modern warmth station devote emerald market physics surface "
    "formal amazing aquatic gesture medical",
    "evoke garden academic agency deal revenue knit reunion decrease magazine flexible company goat repair alarm "
    "military facility clogs aide mandate",
    NULL,
};
static const char* const VEC31[] = {
    "river deal academic acid average forbid pistol peanut custody bike class aunt hairy merit valid flexible learn "
    "ajar very easel",
    "river deal academic agency camera amuse lungs numb isolate display smear piece traffic worthy year patrol crush "
    "fact fancy emission",
    NULL,
};
static const char* const VEC32[] = {
    "wildlife deal beard romp alcohol space mild usual clothes union nuclear testify course research heat listen task "
    "location thank hospital slice smell failure fawn helpful priest ambition average recover lecture process dough "
    "stadium",
    NULL,
};
static const char* const VEC33[] = {
    "wildlife deal decision scared acne fatal snake paces obtain election dryer dominant romp tactics railroad marvel "
    "trust helpful flip peanut theory theater photo luck install entrance taxi step oven network dictate intimate "
    "listen",
    "wildlife deal decision smug ancestor genuine move huge cubic strategy smell game costume extend swimming false "
    "desire fake traffic vegan senior twice timber submit leader payroll fraction apart exact forward pulse tidy "
    "install",
    NULL,
};
static const char* const VEC34[] = {
    "wildlife deal decision shadow analysis adjust bulb skunk muscle mandate obesity total guitar coal gravity carve "
    "slim jacket ruin rebuild ancestor numerous hour mortgage require herd maiden public ceiling pecan pickup shadow "
    "club",
    "wildlife deal beard romp alcohol space mild usual clothes union nuclear testify course research heat listen task "
    "location thank hospital slice smell failure fawn helpful priest ambition average recover lecture process dough "
    "stadium",
    NULL,
};
static const char* const VEC35[] = {
    "wildlife deal ceramic round aluminum pitch goat racism employer miracle percent math decision episode dramatic "
    "editor lily prospect program scene rebuild display sympathy have single mustang junction relate often chemical "
    "society wits estate",
    "wildlife deal decision scared acne fatal snake paces obtain election dryer dominant romp tactics railroad marvel "
    "trust helpful flip peanut theory theater photo luck install entrance taxi step oven network dictate intimate "
    "listen",
    "wildlife deal ceramic scatter argue equip vampire together ruin reject literary rival distance aquatic agency "
    "teammate rebound false argue miracle stay again blessing peaceful unknown cover beard acid island language debris "
    "industry idle",
    "wildlife deal ceramic snake agree voter main lecture axis kitchen physics arcade velvet spine idea scroll promise "
    "platform firm sharp patrol divorce ancestor fantasy forbid goat ajar believe swimming cowboy symbolic plastic "
    "spelling",
    "wildlife deal decision shadow analysis adjust bulb skunk muscle mandate obesity total guitar coal gravity carve "
    "slim jacket ruin rebuild ancestor numerous hour mortgage require herd maiden public ceiling pecan pickup shadow "
    "club",
    NULL,
};
static const char* const VEC36[] = {
    "wildlife deal decision scared acne fatal snake paces obtain election dryer dominant romp tactics railroad marvel "
    "trust helpful flip peanut theory theater photo luck install entrance taxi step oven network dictate intimate "
    "listen",
    "wildlife deal beard romp alcohol space mild usual clothes union nuclear testify course research heat listen task "
    "location thank hospital slice smell failure fawn helpful priest ambition average recover lecture process dough "
    "stadium",
    "wildlife deal decision smug ancestor genuine move huge cubic strategy smell game costume extend swimming false "
    "desire fake traffic vegan senior twice timber submit leader payroll fraction apart exact forward pulse tidy "
    "install",
    NULL,
};
static const char* const VEC37[] = {
    "wildlife deal beard romp alcohol space mild usual clothes union nuclear testify course research heat listen task "
    "location thank hospital slice smell failure fawn helpful priest ambition average recover lecture process dough "
    "stadium",
    "wildlife deal acrobat romp anxiety axis starting require metric flexible geology game drove editor edge screw "
    "helpful have huge holy making pitch unknown carve holiday numb glasses survive already tenant adapt goat fangs",
    NULL,
};
static const char* const VEC38[] = {
    "junk necklace academic academic acne isolate join hesitate lunar roster dough calcium chemical ladybug amount "
    "mobile glasses verify cylinder",
    NULL,
};
static const char* const VEC39[] = {
    "fraction necklace academic academic award teammate mouse regular testify coding building member verdict purchase "
    "blind camera duration email prepare spirit quarter",
    NULL,
};
static const char* const VEC40[] = {
    "herald flea academic cage avoid space trend estate dryer hairy evoke eyebrow improve airline artwork garlic "
    "premium duration prevent oven",
    "herald flea academic client blue skunk class goat luxury deny presence impulse graduate clay join blanket bulge "
    "survive dish necklace",
    "herald flea academic acne advance fused brother frozen broken game ranked ajar already believe check install "
    "theory angry exercise adult",
    NULL,
};
static const char* const VEC41[] = {
    "testify swimming academic academic column loyalty smear include exotic bedroom exotic wrist lobe cover grief "
    "golden smart junior estimate learn",
    NULL,
};
static const char* const VEC42[] = {
    "enemy favorite academic acid cowboy phrase havoc level response walnut budget painting inside trash adjust froth "
    "kitchen learn tidy punish",
    "enemy favorite academic always academic sniff script carpet romp kind promise scatter center unfair training "
    "emphasis evening belong fake enforce",
    NULL,
};
static const char* const VEC43[] = {
    "impulse calcium academic academic alcohol sugar lyrics pajamas column facility finance tension extend space "
    "birthday rainbow swimming purple syndrome facility trial warn duration snapshot shadow hormone rhyme public spine "
    "counter easy hawk album",
    NULL,
};
static const char* const VEC44[] = {
    "western apart academic always artist resident briefing sugar woman oven coding club ajar merit pecan answer "
    "prisoner artist fraction amount desktop mild false necklace muscle photo wealthy alpha category unwrap spew "
    "losing making",
    "western apart academic acid answer ancient auction flip image penalty oasis beaver multiple thunder problem "
    "switch alive heat inherit superior teaspoon explain blanket pencil numb lend punish endless aunt garlic humidity "
    "kidney observe",
    NULL,
};

static const slip39_vector_t VECTORS[] = {
    { VEC00, "bb54aac4b89dc868ba37d9cc21b2cece" },
    { VEC01, "" },
    { VEC02, "" },
    { VEC03, "b43ceb7e57a0ea8766221624d01b0864" },
    { VEC04, "" },
    { VEC05, "" },
    { VEC06, "" },
    { VEC07, "" },
    { VEC08, "" },
    { VEC09, "" },
    { VEC10, "" },
    { VEC11, "" },
    { VEC12, "" },
    { VEC13, "" },
    { VEC14, "" },
    { VEC15, "" },
    { VEC16, "7c3397a292a5941682d7a4ae2d898d11" },
    { VEC17, "7c3397a292a5941682d7a4ae2d898d11" },
    { VEC18, "7c3397a292a5941682d7a4ae2d898d11" },
    { VEC19, "989baf9dcaad5b10ca33dfd8cc75e42477025dce88ae83e75a230086a0e00e92" },
    { VEC20, "" },
    { VEC21, "" },
    { VEC22, "c938b319067687e990e05e0da0ecce1278f75ff58d9853f19dcaeed5de104aae" },
    { VEC23, "" },
    { VEC24, "" },
    { VEC25, "" },
    { VEC26, "" },
    { VEC27, "" },
    { VEC28, "" },
    { VEC29, "" },
    { VEC30, "" },
    { VEC31, "" },
    { VEC32, "" },
    { VEC33, "" },
    { VEC34, "" },
    { VEC35, "5385577c8cfc6c1a8aa0f7f10ecde0a3318493262591e78b8c14c6686167123b" },
    { VEC36, "5385577c8cfc6c1a8aa0f7f10ecde0a3318493262591e78b8c14c6686167123b" },
    { VEC37, "5385577c8cfc6c1a8aa0f7f10ecde0a3318493262591e78b8c14c6686167123b" },
    { VEC38, "" },
    { VEC39, "" },
    { VEC40, "ad6f2ad8b59bbbaa01369b9006208d9a" },
    { VEC41, "1679b4516e0ee5954351d288a838f45e" },
    { VEC42, "48b1a4b80b8c209ad42c33672bdaa428" },
    { VEC43, "8340611602fe91af634a5f4608377b5235fa2d757c51d720c0c7656249a3035f" },
    { VEC44, "8dc652d6d6cd370d8c963141f6d79ba440300f25c467302c1d966bff8f62300d" },
};
// END GENERATED

// Collects every mnemonic of one record and combines them, stopping at the first rejection.
// Returns the error that stopped it, or SLIP39_OK with the master secret written out.
static slip39_err_t run_vector(
    const slip39_vector_t* vector, const char* passphrase, uint8_t* secret, size_t* secret_len)
{
    slip39_ctx_t ctx;
    slip39_init(&ctx);

    slip39_err_t rc = SLIP39_OK;
    for (size_t i = 0; vector->mnemonics[i] && rc == SLIP39_OK; ++i) {
        slip39_share_t share;
        rc = slip39_parse_share(vector->mnemonics[i], strlen(vector->mnemonics[i]), &share);
        if (rc == SLIP39_OK) {
            rc = slip39_add_share(&ctx, &share);
        }
        wally_bzero(&share, sizeof(share));
    }

    *secret_len = 0;
    if (rc == SLIP39_OK) {
        rc = slip39_combine(&ctx, passphrase, secret, ctx.value_len);
        if (rc == SLIP39_OK) {
            *secret_len = ctx.value_len;
        }
    }

    slip39_clear(&ctx);
    return rc;
}

static bool test_vectors(void)
{
    size_t rejections[SLIP39_ERR_DIGEST + 1] = { 0 };
    size_t num_valid = 0;
    size_t num_invalid = 0;

    for (size_t i = 0; i < sizeof(VECTORS) / sizeof(VECTORS[0]); ++i) {
        uint8_t secret[SLIP39_MASTER_SECRET_MAX];
        size_t secret_len = 0;
        const slip39_err_t rc = run_vector(&VECTORS[i], VECTOR_PASSPHRASE, secret, &secret_len);

        if (!VECTORS[i].secret[0]) {
            // Must be rejected, and we record which rule caught it.
            if (rc == SLIP39_OK) {
                JADE_LOGE("SLIP39 vector %u should have been rejected", (unsigned)i);
                FAIL();
            }
            JADE_ASSERT((size_t)rc < sizeof(rejections) / sizeof(rejections[0]));
            ++rejections[rc];
            ++num_invalid;
            continue;
        }

        if (rc != SLIP39_OK) {
            JADE_LOGE("SLIP39 vector %u rejected: %s", (unsigned)i, slip39_error_message(rc));
            FAIL();
        }

        uint8_t expected[SLIP39_MASTER_SECRET_MAX];
        size_t written = 0;
        if (wally_hex_to_bytes(VECTORS[i].secret, expected, sizeof(expected), &written) != WALLY_OK) {
            FAIL();
        }
        if (written != secret_len || memcmp(expected, secret, written)) {
            JADE_LOGE("SLIP39 vector %u recovered the wrong master secret", (unsigned)i);
            FAIL();
        }
        ++num_valid;
        wally_bzero(secret, sizeof(secret));
    }

    JADE_LOGI("SLIP39 vectors: %u recovered, %u rejected", (unsigned)num_valid, (unsigned)num_invalid);
    for (size_t i = 1; i < sizeof(rejections) / sizeof(rejections[0]); ++i) {
        if (rejections[i]) {
            JADE_LOGI("  rejected by \"%s\": %u", slip39_error_message((slip39_err_t)i), (unsigned)rejections[i]);
        }
    }
    return num_valid == 15 && num_invalid == 30;
}

// Positive control.  A share that the run above accepts, with one word swapped for another
// word of the same wordlist, must be rejected - otherwise a checksum that always returned
// true would go unnoticed and every record above would still pass.
static bool test_corrupted_share_is_rejected(void)
{
    const char* const good = VECTORS[0].mnemonics[0];
    const char* const last = strrchr(good, ' ');
    if (!last) {
        FAIL();
    }

    char corrupted[256];
    const size_t prefix_len = (size_t)(last - good) + 1;
    if (prefix_len + sizeof("academic") > sizeof(corrupted)) {
        FAIL();
    }
    memcpy(corrupted, good, prefix_len);
    memcpy(corrupted + prefix_len, "academic", sizeof("academic"));
    if (!strcmp(corrupted, good)) {
        // The vector already ended with that word, so nothing was corrupted and the check
        // below would pass for the wrong reason.
        FAIL();
    }

    slip39_share_t share;
    const slip39_err_t rc = slip39_parse_share(corrupted, strlen(corrupted), &share);
    wally_bzero(&share, sizeof(share));
    if (rc != SLIP39_ERR_CHECKSUM) {
        JADE_LOGE("SLIP39 corrupted share was not caught by the checksum: %s", slip39_error_message(rc));
        FAIL();
    }
    return true;
}

// The design note claims the vectors do not decrypt with an empty passphrase.  Measure it:
// the same record run with no passphrase must give a different master secret, not an error.
// This is also the only check here that the passphrase reaches the Feistel rounds at all.
static bool test_empty_passphrase_gives_a_different_secret(void)
{
    uint8_t secret[SLIP39_MASTER_SECRET_MAX];
    size_t secret_len = 0;
    if (run_vector(&VECTORS[0], "", secret, &secret_len) != SLIP39_OK) {
        FAIL();
    }

    uint8_t expected[SLIP39_MASTER_SECRET_MAX];
    size_t written = 0;
    if (wally_hex_to_bytes(VECTORS[0].secret, expected, sizeof(expected), &written) != WALLY_OK) {
        FAIL();
    }
    const bool differs = written != secret_len || memcmp(expected, secret, written);
    wally_bzero(secret, sizeof(secret));
    if (!differs) {
        FAIL();
    }
    return true;
}

// A word that is not in the wordlist must be refused before anything else looks at the share.
// No record above can reach this: all of them are built from the wordlist, so a lookup that
// silently accepted an unknown word would leave every one of the 45 decisions unchanged.
static bool test_unknown_word_is_rejected(void)
{
    const char* const good = VECTORS[0].mnemonics[0];
    const char* const last = strrchr(good, ' ');
    if (!last) {
        FAIL();
    }

    // "bitcoin" is in no wordlist entry, and no entry begins "bitc" either, so the binary
    // search cannot land on a prefix match.
    char corrupted[256];
    const size_t prefix_len = (size_t)(last - good) + 1;
    if (prefix_len + sizeof("bitcoin") > sizeof(corrupted)) {
        FAIL();
    }
    memcpy(corrupted, good, prefix_len);
    memcpy(corrupted + prefix_len, "bitcoin", sizeof("bitcoin"));

    slip39_share_t share;
    const slip39_err_t rc = slip39_parse_share(corrupted, strlen(corrupted), &share);
    wally_bzero(&share, sizeof(share));
    if (rc != SLIP39_ERR_WORD) {
        JADE_LOGE("SLIP39 unknown word was not rejected: %s", slip39_error_message(rc));
        FAIL();
    }
    return true;
}

// The first valid record carrying more than one share, so the check below does not hard code
// an index into a generated table.
static const slip39_vector_t* first_multi_share_vector(void)
{
    for (size_t i = 0; i < sizeof(VECTORS) / sizeof(VECTORS[0]); ++i) {
        if (VECTORS[i].secret[0] && VECTORS[i].mnemonics[0] && VECTORS[i].mnemonics[1]) {
            return &VECTORS[i];
        }
    }
    return NULL;
}

// The same share offered twice must be refused.  This is the one place the fork knowingly
// parts from the reference, which collects shares into a set and drops an identical repeat
// without saying so (main/slip39.c).  No record can reach it either, because none of them
// repeats a share, so without this check the divergence would go unmeasured.
static bool test_repeated_share_is_rejected(void)
{
    const slip39_vector_t* const vector = first_multi_share_vector();
    if (!vector) {
        FAIL();
    }

    slip39_share_t share;
    if (slip39_parse_share(vector->mnemonics[0], strlen(vector->mnemonics[0]), &share) != SLIP39_OK) {
        FAIL();
    }

    slip39_ctx_t ctx;
    slip39_init(&ctx);
    slip39_err_t rc = slip39_add_share(&ctx, &share);
    if (rc == SLIP39_OK) {
        rc = slip39_add_share(&ctx, &share);
    }
    wally_bzero(&share, sizeof(share));
    slip39_clear(&ctx);

    if (rc != SLIP39_ERR_DUPLICATE) {
        JADE_LOGE("SLIP39 repeated share was not rejected: %s", slip39_error_message(rc));
        FAIL();
    }
    return true;
}

bool test_slip39(void)
{
    JADE_LOGI("Testing SLIP39 share recovery");

    return test_vectors() && test_corrupted_share_is_rejected() && test_unknown_word_is_rejected()
        && test_repeated_share_is_rejected() && test_empty_passphrase_gives_a_different_secret();
}

bool debug_selfcheck(jade_process_t* process)
{
    if (!test_slip39()) {
        FAIL();
    }
    return true;
}
